[[redirects]]
  from = "/index.html"
  to = "/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/books"
  to = "/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/about"
  to = "/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/newsletter"
  to = "/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
from = "/contact"
to = "/"
status = 200
force = true
headers = {X-From = "Netlify"}

[build]
  functions = "netlify/functions"